name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js v19.3.0
      uses: actions/setup-node@v3
      with:
        node-version: '19.3.0'
    - name: Install dependencies
      run: npm install
      env:
        NODE_ENV: production
    - name: Vue.JS
      run: npm install -g @vue/cli-service && npm i vue-template-compiler --save-dev
    - name: Build app
      run: npm run build
    - name: Setup Github
      run:  git config --global user.email "crayvian@pm.me" && git config --global user.name "Crayvian"
    - name: Deploy to GitHub Pages
      run: npm run deploy
